/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBottlenecksRouteImport } from './routes/_authenticated/bottlenecks'
import { Route as AuthenticatedDiagnosisRouteImport } from './routes/_authenticated/diagnosis'
import { Route as AuthenticatedHistoricalRouteImport } from './routes/_authenticated/historical'
import { Route as AuthenticatedInterventionsRouteImport } from './routes/_authenticated/interventions'
import { Route as AuthenticatedLiveOrdersRouteImport } from './routes/_authenticated/live-orders'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedWorkforceRouteImport } from './routes/_authenticated/workforce'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as ApiPublicRefreshDemoRouteImport } from './routes/api/public/refresh-demo'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBottlenecksRoute =
  AuthenticatedBottlenecksRouteImport.update({
    id: '/bottlenecks',
    path: '/bottlenecks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosisRoute = AuthenticatedDiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricalRoute = AuthenticatedHistoricalRouteImport.update({
  id: '/historical',
  path: '/historical',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterventionsRoute =
  AuthenticatedInterventionsRouteImport.update({
    id: '/interventions',
    path: '/interventions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveOrdersRoute = AuthenticatedLiveOrdersRouteImport.update({
  id: '/live-orders',
  path: '/live-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkforceRoute = AuthenticatedWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicRefreshDemoRoute = ApiPublicRefreshDemoRouteImport.update({
  id: '/api/public/refresh-demo',
  path: '/api/public/refresh-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/bottlenecks': typeof AuthenticatedBottlenecksRoute
  '/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/historical': typeof AuthenticatedHistoricalRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/live-orders': typeof AuthenticatedLiveOrdersRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/public/refresh-demo': typeof ApiPublicRefreshDemoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/bottlenecks': typeof AuthenticatedBottlenecksRoute
  '/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/historical': typeof AuthenticatedHistoricalRoute
  '/interventions': typeof AuthenticatedInterventionsRoute
  '/live-orders': typeof AuthenticatedLiveOrdersRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/': typeof AuthenticatedIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/public/refresh-demo': typeof ApiPublicRefreshDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bottlenecks': typeof AuthenticatedBottlenecksRoute
  '/_authenticated/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/_authenticated/historical': typeof AuthenticatedHistoricalRoute
  '/_authenticated/interventions': typeof AuthenticatedInterventionsRoute
  '/_authenticated/live-orders': typeof AuthenticatedLiveOrdersRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/workforce': typeof AuthenticatedWorkforceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/api/public/refresh-demo': typeof ApiPublicRefreshDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bottlenecks'
    | '/diagnosis'
    | '/historical'
    | '/interventions'
    | '/live-orders'
    | '/recommendations'
    | '/workforce'
    | '/orders/$orderId'
    | '/api/public/refresh-demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/bottlenecks'
    | '/diagnosis'
    | '/historical'
    | '/interventions'
    | '/live-orders'
    | '/recommendations'
    | '/workforce'
    | '/'
    | '/orders/$orderId'
    | '/api/public/refresh-demo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bottlenecks'
    | '/_authenticated/diagnosis'
    | '/_authenticated/historical'
    | '/_authenticated/interventions'
    | '/_authenticated/live-orders'
    | '/_authenticated/recommendations'
    | '/_authenticated/workforce'
    | '/_authenticated/'
    | '/_authenticated/orders/$orderId'
    | '/api/public/refresh-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRefreshDemoRoute: typeof ApiPublicRefreshDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bottlenecks': {
      id: '/_authenticated/bottlenecks'
      path: '/bottlenecks'
      fullPath: '/bottlenecks'
      preLoaderRoute: typeof AuthenticatedBottlenecksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnosis': {
      id: '/_authenticated/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof AuthenticatedDiagnosisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historical': {
      id: '/_authenticated/historical'
      path: '/historical'
      fullPath: '/historical'
      preLoaderRoute: typeof AuthenticatedHistoricalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interventions': {
      id: '/_authenticated/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof AuthenticatedInterventionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-orders': {
      id: '/_authenticated/live-orders'
      path: '/live-orders'
      fullPath: '/live-orders'
      preLoaderRoute: typeof AuthenticatedLiveOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workforce': {
      id: '/_authenticated/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof AuthenticatedWorkforceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/refresh-demo': {
      id: '/api/public/refresh-demo'
      path: '/api/public/refresh-demo'
      fullPath: '/api/public/refresh-demo'
      preLoaderRoute: typeof ApiPublicRefreshDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBottlenecksRoute: typeof AuthenticatedBottlenecksRoute
  AuthenticatedDiagnosisRoute: typeof AuthenticatedDiagnosisRoute
  AuthenticatedHistoricalRoute: typeof AuthenticatedHistoricalRoute
  AuthenticatedInterventionsRoute: typeof AuthenticatedInterventionsRoute
  AuthenticatedLiveOrdersRoute: typeof AuthenticatedLiveOrdersRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedWorkforceRoute: typeof AuthenticatedWorkforceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBottlenecksRoute: AuthenticatedBottlenecksRoute,
  AuthenticatedDiagnosisRoute: AuthenticatedDiagnosisRoute,
  AuthenticatedHistoricalRoute: AuthenticatedHistoricalRoute,
  AuthenticatedInterventionsRoute: AuthenticatedInterventionsRoute,
  AuthenticatedLiveOrdersRoute: AuthenticatedLiveOrdersRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedWorkforceRoute: AuthenticatedWorkforceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRefreshDemoRoute: ApiPublicRefreshDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
